In [3]:
import torch

In [5]:
a = [[11,12,13],[21,22,23],[31,32,33]]
A = torch.tensor(a)
print(A)

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [11]:
print(A.ndimension()) # aka rank
print(A.shape)
print(A.size()) # use size method to get shape attribute
print(A.numel()) # total number of elements

2
torch.Size([3, 3])
torch.Size([3, 3])
9


In [14]:
print(A[0][0])
print(A[1][1])
print(A[2][2])

tensor(11)
tensor(22)
tensor(33)


In [21]:
x = [[1,0],[0,1]]
y = [[2,1],[3,2]]
x, y = torch.tensor(x), torch.tensor(y)

z=x+y
print(z)

z=x-y
print(z)

#hadamard product
z=x*y
print(z)

z=x/y
print(z)

z=x+1
print(z)

tensor([[3, 1],
        [3, 3]])
tensor([[-1, -1],
        [-3, -1]])
tensor([[2, 0],
        [0, 2]])
tensor([[0, 0],
        [0, 0]])
tensor([[2, 1],
        [1, 2]])


In [24]:
#true matrix multiplication is more complicated than just *

A = [[0,1,1],[1,0,1]]
B = [[1,1],[1,1],[-1,1]]
A, B = torch.tensor(A), torch.tensor(B)
C = torch.mm(A,B)
print(C)

tensor([[0, 2],
        [0, 2]])


In [25]:
# Practice

a=torch.tensor([[0,1,1],[1,0,1]])
print(a.size())
print(a.ndimension())

torch.Size([2, 3])
2


In [28]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print(A_times_B)

tensor([[0, 2],
        [0, 2]])
